core_app_root/ai_application_dashboard/urls.py
from django.urls import path
from core_app_root.ai_application_dashboard import views

app_name="dashboard_app"
urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('dashboard/search/',views.search,name='search'),
    path('dashboard/books/',views.book,name='books'),
    path('dashboard/books/recommendation/',views.recommendation,name='recommendation'),
    path('dashboard/books/save/',views.save_page,name='save'),
    path('dashboard/books/summarize/',views.summarize,name='summarize'),
    path('dashboard/citation/',views.reference_generator,name='citation')
   
    
]

core_app_root/security/urls.py
from django.urls import path
from .views import signup,login
from core_app_root.security import views
app_name='security'
urlpatterns = [
    path("auth/signup/",signup,name='signup'),
    path('auth/login/',login,name='login'),
    path('auth/login/facial/',views.face_login,name='facial')
]

core_app_root/urls.py
from django.urls import path
from . import views
from .views import captureindex, detect, trainer, create_dataset
from .views import capture_face, login_with_face

app_name='core_app_root'
urlpatterns=[
    path('',views.index,name='index'),
    path('image/', captureindex),
    path('image/createdataset', create_dataset,name='createdataset'),
    path('image/detect', detect,name='detect'),
    path('image/train', trainer,name='train'),
    path('capture_face/', capture_face, name='capture_face'),
    path('login_with_face/', login_with_face, name='login_with_face'),
]

elibraryplatform/urls.py
from django.contrib import admin
import django.urls
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.urls import include
from rest_framework import permissions
from django.urls import path,re_path,include
from django.urls import path, include
from core_app_root.security import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.urls import path

schema_view = get_schema_view(
   openapi.Info(
      title="Elibraryplatform Api",
      default_version='v1',
      description="Elibraryplatform App Documentation",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="kezechristian@gmail.com"),
      license=openapi.License(name="Elibraryplatform licence"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[]
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('',include('core_app_root.urls')),
    path('library/',include('core_app_root.ai_application_dashboard.urls')),
    path('ai/',include('core_app_root.ai_applications.routers')),
    path('',include('core_app_root.security.urls')),
    path('',include(('core_app_root.security.user.routers','core_app_root.security.user'))),
    path('',include(('core_app_root.security.auth.routers','core_app_root.security.auth'))),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', views.face_login, name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    
    


    


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT)

core_app_root/ai_applications/models.py
from django.db import models

# Create your models here.
class TextModel(models.Model):
    text_body=models.TextField(null=True,blank=True)

core_app_root/models.py
from django.db import models

# Create your models here.

core_app_root/security/models.py
from django.db import models

# Create your models here.
from core_app_root.security.user.models import User
from django.db import models
import time
import os

def content_file_name(instance, filename):
    timestr = time.strftime("%Y%m%d-%H%M%S")
    name, extension = os.path.splitext(filename)
    return os.path.join('content', instance.user.username, timestr + extension)

class UserFaceImage(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=content_file_name, blank=False)

core_app_root/ai_application_dashboard/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    
# class BookSummarizeForm(forms.Form):
#     book_file=forms.FileField(max_length=5000)

core_app_root/security/forms.py
from django import forms
from core_app_root.security.user.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserFaceImage
from .utils import base64_file


class UserCreationForm(UserCreationForm):
    image = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = User
        fields = ['id','email', 'username','password','confirm_password','phone_number']


    def save(self, commit=True):
        if not commit:
            raise NotImplementedError("Can't create User and UserFaceImage without database save")
        user = super(UserCreationForm, self).save(commit=True)
        image = base64_file(self.data['image'])
        face_image = UserFaceImage(user=user, image=image)
        face_image.save()
        return user

class AuthenticationForm(AuthenticationForm):
    image = forms.CharField(widget=forms.HiddenInput())

core_app_root/ai_application_dashboard/views.py
import gzip
import threading
import webbrowser
from django.shortcuts import render
import threading
from django.core.files.storage import FileSystemStorage
# Create your views here.

from . import extract_txt
# from . import summarizetxt
import ast
from ast import literal_eval
from django.shortcuts import render
from django.http import HttpResponse, StreamingHttpResponse
from bs4 import BeautifulSoup
import requests
from .forms import SearchForm
from pycite.pycite import PyCite
from core_app_root.ai_application_dashboard import models
def dashboard(request):
    return render(request,"dashboard/dashboard.html")

from django.shortcuts import render
from .forms import SearchForm
# import webview
no_of_search=0
url=""
# def open_search_view_results(url):
    # webview.create_window('Search Results', url)
    # webview.start()


def index(request, *args, **kwargs):
    return render(request, 'index.html')
class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()

    def get_frame(self):
        image = self.frame
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Fetch data from other sites using the query
            url = f'http://localhost' + query
            search_results=fetch_search_results(url)
            # no_of_search=1
            # no_of_search=no_of_search
            # webbrowser.open(url)
            return render(request, 'dashboard/search.html', {'form': form,'search_results':search_results})
        return render(request, 'dashboard/search.html', {'form': form,'search_results':search_results})
        
    else:
        form = SearchForm()
    return render(request, 'dashboard/search.html', {'form': form})

def fetch_search_results(query):
    # Example of fetching data from another site (modify this according to your needs)
    url = '/search?q=' + query
    response = requests.get(url)
    
    soup = BeautifulSoup(response.text, 'html.parser')
    # Extract links from the fetched data
    links = [a['href'] for a in soup.find_all('a', href=True)]
    return links


def book(request):
    list_of_books=models.Book.objects.all()
    context={"book_list":list_of_books,"read_mode":False,"readorshrink":"Read"}
    if request.method=='POST':
        if request.POST['readorshrink']=='Read':
            read_mode=True
            for read_book in list_of_books:
                read_book.number_of_times_read+=1
                read_book.save()
                
            context={"book_list":list_of_books,"read_mode":read_mode,"readorshrink":"Stop Reading"}
                
            # return render(request,'dashboard/books.html',context)
        else:
            read_mode=False
            
            context={"book_list":list_of_books,"read_mode":read_mode,"readorshrink":"Read"}
        
        
    return render(request,'dashboard/books.html',context)

def save_page(request):
    book_to_save={"book":models.Books.objects.all()}
    return render(request,'dashboard/save.html',book_to_save)

def recommendation(request):
    list_of_books=models.Book.objects.all()
    context={"recommended_book_list":[],"read_mode":False,"readorshrink":"Read"}
    
    for read_book in list_of_books:
        read_book.number_of_times_read
        recommended_list=models.RecommendedBook.objects.all()
        if int(read_book.number_of_times_read)>=5:
            context={"recommended_book_list":recommended_list,"read_mode":False,"readorshrink":"Read"}
            return render(request,'dashboard/recommendation.html',context)

            
            
        
    context=context
    return render(request,'dashboard/recommendation.html',context)

# def save_page(request):
#     book_to_save={"book":models.Books.objects.get().save}
#     return render(request,'dashboard/save.html',book_to_save)

def summarize(request):
    context={"upload_message":"Upload Doc","text":""}
    if request.method == 'POST' and request.FILES['book_file']:
        upload_message=f"{request.FILES['book_file']} uploaded"
        context={"upload_message":upload_message,"text":""}
        uploaded_file = request.FILES['book_file']
        fs = FileSystemStorage()
        filename = fs.save(uploaded_file.name, uploaded_file)
        file_path = fs.path(filename)
        
        # Process the uploaded PDF file
        # extract_txt.pdf_to_json(pdf_path=file_path, json_file="extracted_book_text.json")
        
        # Read the extracted text from the JSON file
        with open("extracted_book_text.json", "r") as f:
            pdf_text = f.read()
        
    
        # pdf_text=summarizetxt.generate_summary(str(pdf_text))
        # Now you can do something with the extracted text
        # For example, you could render it in a template
        context={"upload_message":upload_message,"text":pdf_text}
        
        return render(request, 'dashboard/text-summariser.html',context)
    
    return render(request, 'dashboard/text-summariser.html',context)

def reference_generator(request):
    if request.method == 'POST':
        url_text = request.POST['url_of_site'] 
        with open("testlinks.txt","w") as file:
            file.write(url_text)
        # Assuming you have a form with input fields named 'urls'
        my_citations = PyCite(input_file="testlinks.txt",output_file='citations.txt')
        
        citations = my_citations.cite()
        # with open("citations","r") as readFile:
        #     citations
        return render(request, 'dashboard/reference-generator.html', {'citations': citations})

    return render(request,'dashboard/reference-generator.html')

core_app_root/ai_applications/views.py
from django.shortcuts import render

# Create your views here.

core_app_root/security/user/views.py
from django.shortcuts import render

# Create your views here.

core_app_root/security/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
import requests
from django.shortcuts import render
from django.http import JsonResponse
import base64
import numpy as np
from PIL import Image
from io import BytesIO

from rest_framework.response import Response
from .forms import *
# from core_app_root.security import authenticate
# from core_app_root.security.authenticate import FaceIdAuthBackend
from core_app_root.security.forms import AuthenticationForm
from core_app_root.security.utils import prepare_image
from elibraryplatform import settings
from . import base_url
from rest_framework import status
from .forms import UserCreationForm
app_name='security'
def login(request):
    context={"error_messages":""}
    if request.method == 'POST':
            email=request.POST['email']
            password=request.POST['password']
            signin_data={
                "email":email,
                "password":password,
                }
            
            main_url=base_url.main_url+"login/"
            # user = face_id.authenticate(username=email, password=password, face_id=face_image)
            # if user is not None:
            singin_response=requests.post(main_url,json=signin_data)

            if singin_response.status_code==200:
                    
                singin_response=singin_response.json()
                print(singin_response)
                return redirect('dashboard_app:dashboard')
                    
            
            else:
                    # username = form.cleaned_data['email']
                # password = form.cleaned_data['password']
                context={"error_messages":"Check if email and password you entered is correct or not"}
        
    print(context)
    context = context
    return render(request, 'auth/login.html', context)


    


# Create your views here.
def signup(request):
    context={"signupErrorMessages":""}
    if request.method=='POST':
        # form = UserCreationForm(request.POST, request.FILES)
        
        email=request.POST['email']
        username=request.POST['username']
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        
        if str(password)==str(confirm_password):
            signup_data={
            "email":email,
            "username":username,
            "password":password,
            "confirm_password":confirm_password
            }
            main_url=base_url.main_url+"register/"
            singup_response=requests.post(main_url,json=signup_data)

            if singup_response.status_code==201:
                singup_response=singup_response.json()
                print(singup_response)
                # context="Signup Successful"
                # return render(g)
                return redirect('security:login')
                # return redirect('core_app_root:capture_face', user_id=request.user.id)
                
            
            else:
                context = {"signupErrorMessages":["1. Consider checking if your password is upto 8 characters or if username, email already exists in the database , and also check if you entered and confirmed your password "]}
                # full_url=f"{base_url}auth/login"
        else:
        
            context = {"signupErrorMessages":["1. Consider checking if your password is upto 8 characters or if username, email already exists in the database , and also check if you entered and confirmed your password "]}
            # full_url=f"{base_url}auth/login"
    context=context
    print(context)
    return render(request,'auth/signup.html',context)

def face_recognition(request):
    return render(request,'auth/face-recognition.html')

def register(request):
    if  request.method == 'POST':
        form = UserCreationForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']
            # user = authenticate(username=username, password=password)
            # login(request, user)
            return redirect('security:login')
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'django_two_factor_face_auth/signup.html', context)






def face_login(request):
    if request.method == 'POST':
        try:
            data = request.json()
            image_data = data['image']
            format, imgstr = image_data.split(';base64,')
            image = Image.open(BytesIO(base64.b64decode(imgstr)))
            image = np.array(image)

            face_encodings = face_recognition.face_encodings(image)
            if face_encodings:
                user = request.user
                
                user.face_encoding(face_encodings[0])
                user.save()
                return JsonResponse({'success': True})
            else:
                return JsonResponse({'success': False, 'error': 'No face detected'})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})

    return render(request, 'auth/face-recognition.html')

core_app_root/templates/dashboard/books.html
<!DOCTYPE html>
<html>
	{% load static %}
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/favicon" href="{% static './images/ai-logo.svg' %}">
	<link rel="stylesheet" type="text/css" href="{% static './css/index.css' %}">
	<!-- <script src="../js/password.js" defer></script> -->
	<!-- <script src="../js/header.js" defer></script> -->
	<title>Dashboard || Books</title>
</head>
<body>
<!-- Header Section -->
<div id="scroll-top"></div>
<div class="dashboard-container books grid-2">
<header class="dashboard-header-container">
 <a class="logo-img-container">
	<img src="{% static './images/ai-logo.svg' %}" alt="logo">
 </a>
 <div class="dashboard-nav-container">
	<nav class="dashboard-side-menu">
		<ul class="list">
		  <li class="inner-flex-2 active">
			<div class="img-icon">
				<img src="{% static './images/dashboard/dashboard-icon.svg' %}" alt="dashboard">
			</div>
			<a href="./dashboard.html">dashboard</a>
		   </li>
		  <li class="inner-flex-2">
			<div class="img-icon">
				<img src="{% static './images/dashboard/search-icon.svg' %}" alt="search">
			</div>
			<a href="{% url 'dashboard_app:search' %}">search</a>
		   </li>
		  <li class="inner-flex-2">
			<div class="img-icon">
				<img src="{% static './images/dashboard/books-icon.svg' %}" alt="books">
			</div>
			<a href="{% url 'dashboard_app:books' %}">books</a>
		   </li>
		  <li class="inner-flex-2">
			<div class="img-icon">
				<img src="{% static './images/dashboard/recommendation-icon.svg' %}" alt="recommedation">
			</div>
			<a href="{% url 'dashboard_app:recommendation' %}">recommendations</a>
		   </li>
		  <li class="inner-flex-2">
			<div class="img-icon">
				<img src="{% static './images/dashboard/saved-icon.svg' %}" alt="save">
			</div>
			<a href="{% url 'dashboard_app:save' %}">saved</a>
		   </li>
		  <li class="inner-flex-2">
			<div class="img-icon">
				<img src="{% static './images/dashboard/text-summary-icon.svg' %}" alt="text summary">
			</div>
			<a href="{% url 'dashboard_app:summarize' %}">text summarizer</a>
		   </li>
		   <li class="inner-flex-2 active">
			<div class="img-icon">
				<img src="{% static './images/dashboard/icons/active-referance-icon.svg' %}" alt="reference generator">
			</div>
			<a href="{% url 'dashboard_app:citation' %}">reference generator</a>
		   </li>
		</ul>
	</nav>
 </div>
</header>
<main class="main-container">

{% for all_book in book_list %}
<div class="section-one">
	<div class="inner-navigations">
        <div class="flex-item">
            <a href="./search.html" class="nav-span left">
                <svg width="11" height="16" viewBox="0 0 11 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9.18838 14.7365L9.8623 14.0995L3.34788 7.942L9.8623 1.78452L9.18838 1.14752L2.00002 7.942L9.18838 14.7365Z" fill="white" stroke="white" stroke-width="1.5"/>
                    </svg>
                    
            </a>
            <a class="nav-span right" href="./recommendation.html">
                <svg width="11" height="16" viewBox="0 0 11 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2.44218 1.10966L1.76825 1.74666L8.28268 7.90413L1.76825 14.0616L2.44218 14.6986L9.63054 7.90413L2.44218 1.10966Z" fill="white" stroke="white" stroke-width="1.5"/>
                    </svg>
                    
            </a>
        </div>
        <div class="flex-item">
            <div class="img-container">
                <img src="{% static './images/dashboard/icons/profile-icon.svg' %}" alt="user profile">
            </div>
        </div>
	</div>
    <div class="flex-container-2">
        <div class="flex-item">
            <div class="img-container">
                <img src="{{all_book.cover.url}}" alt="things fall apart">
            </div>
        </div>
        <div class="flex-item">
            <h2>{{all_book.title}}</h2>
            <h4><span class="author-title">Author:</span> <span class="author-name">Savi Stroutman</span></h4>
            <p>{{all_book.get_first_30_words}}</p>
            <div class="book-details">
                <h4>Category: <span class="description"> Romance</span></h4>
                <h4>Language: <span class="description"> English</span></h4>
                <h4>ISBN: <span class="description">950974512</span></h4>
		
		<h4>Number of Times Read: <span class="description">{{all_book.number_of_times_read}}</span></h4>

				
            </div>
        </div>
    </div>
	<p></p>
</div>

<div class="extracted-chapters">

    <div class="chapter-container">
<form action="{% url 'dashboard_app:books' %}"  method="post">
	{% csrf_token %}
	       
			<input type="submit" value="{{readorshrink}}" style="font-size: 30px;margin:20px;padding-left:20px;padding-right:20px" name="readorshrink">
			
			{% if read_mode  %}
			<p>
        
				{{all_book.book_details}}
				
			</p>
			{% else %}
        <p hidden>
        
			{{all_book.book_details}}
			
        </p>
		{% endif %}
</form>
        
    </div>
</div>
{% endfor %}
<div class="more-books">
	<div>
		<h4>more for you</h4>
	</div>
	<div class="books-card-section grid-container-5">
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-1.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-2.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-3.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-4.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-5.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
	</div>
	<div class="books-card-section grid-container-5">
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-1.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-2.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-3.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-4.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
		<figure class="book-card">
			<div class="top-section">
				<div class="img-container">
					<img src="{% static './images/dashboard/book-covers/cover-5.svg' %}" alt="book cover 1">
				</div>
			</div>
			<div class="bottom-section">
				<h5 class="title">things fall apart</h5>
				<p class="author">chinua achebe</p>
			</div>
			<span class="love-icon">
				<div class="img-container">
					<img src="{% static './images/dashboard/icons/love-icon.svg' %}" alt="love">
				</div>
			</span>
		</figure>
	</div>
</div>
</div>
<footer class="footer-container">
	<!-- <section class="footer-section"></section> -->
	<section class="footer-section">
	 <div class="flex-container">
		<div class="flex-item">
		   <ul class="list-menu">
			  <li><a href="#">discover</a>
				 <ul class="nested-list-menu">
					<li><a href="./dashboard/dashboard.html">dashboard</a></li>
					<li><a href="#">advanced search</a></li>
					<li><a href="#">saved books</a></li>
					<li><a href="#">recommended books</a></li>
					<li><a href="#">text summarizer books</a></li>
					<li><a href="#">all books</a></li>
				 </ul>
			  </li>
			  <li>
				 <div class="img-container">
					   <img src="{% static './images/ai-logo.svg' %}" alt="logo">
				 </div>
					<hr>
					<div class="address">
					   <address>
						  <p><a href="tel:+234 9017912839">+234 90170912839</a></p>
						  <p><a href="mailto:solobachi02@gmail.com">solobachi02@gmail.com</a></p>
					   </address>
				 </div>
			  </li>
			  <li>
			   <a href="#">help</a>
			   <ul class="nested-list-menu">
				 <li><a href="#">report a problem</a></li>
				 <li><a href="#">help center</a></li>
			  </ul>
			  </li>
			  <li>
			   <a href="#">info</a>
			   <ul class="nested-list-menu">
				 <li><a href="#">about us</a></li>
				 <li><a href="#">works</a></li>
				 <li><a href="#">contact us</a></li>
			  </ul>
			  </li>
		   </ul>
		</div>

	 </div>
	 <div class="footer-inner-flex">
		<div class="flex-item">
		   <span>&copy; 2024 &dash; copyright</span>
		</div>
		<div class="flex-item">
		   <a class="scroll-top-container" href="#scroll-top">
			  <img src="../icons/scroll-top.svg' %}" alt="scroll">
		   </a>
		</div>
	 </div>
	</section>
 </footer>
</main>
</div>
</body>
</html>

core_app_root/templates/dashboard/search_results.html
<!-- search_app/templates/search_app/search_results.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>
    <ul>
        {% for link in search_results %}
            <li><a href="{{ link }}">{{ link }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>